version: '3'

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=pedrofaria
        - POSTGRES_DB=pedrofaria
    ports:
      - 5432:5432
    volumes:
      - ./db_data/pg:/data/postgresql

  influx:
    image: influxdb
    hostname: influx
    container_name: influxdb
    environment:
      - INFLUXDB_DB=INEGI_INFLUX
    volumes: 
      - ./db_data/in:/data/influxdb

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongodb
    volumes:
      - ./db_data/mn:/data/mongodb
    ports:
      - 27017:27017
    command: mongod --smallfiles

  web:
    depends_on:
      - postgres
      - influx
      - mongo
    build: .
    container_name: django_server
    environment:
      WAIT_HOSTS: postgres, influx, mongo
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./INEGI:/code
    ports:
      - "8000:8000"
