# Generated by Django 2.1.7 on 2019-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_tower_c_6a0ada_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_tower_c_56bc0f_idx',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='towers',
            new_name='stations',
        ),
        migrations.RenameField(
            model_name='datasetpg',
            old_name='tower_code',
            new_name='station_code',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='towers',
            new_name='stations',
        ),
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['station_code', 'time_stamp'], name='main_app_da_station_5ee5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['station_code'], name='main_app_da_station_074662_idx'),
        ),
    ]
