# Generated by Django 2.1.7 on 2019-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190319_1758'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_station_5ee5e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_station_074662_idx',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='stations',
            new_name='towers',
        ),
        migrations.RenameField(
            model_name='datasetpg',
            old_name='station_code',
            new_name='tower_code',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='stations',
            new_name='towers',
        ),
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['tower_code', 'time_stamp'], name='main_app_da_tower_c_6a0ada_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['tower_code'], name='main_app_da_tower_c_56bc0f_idx'),
        ),
    ]
