# Generated by Django 2.1.7 on 2019-03-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190310_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpg',
            name='tower_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Tower'),
        ),
    ]
