# Generated by Django 2.1.7 on 2019-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190319_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='group_type',
            field=models.ForeignKey(on_delete=0, to='main_app.UserGroupType'),
        ),
    ]
