# Generated by Django 2.1.7 on 2019-03-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190320_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCalibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TestEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, unique=True)),
                ('calibrations', models.ForeignKey(blank=True, null=True, on_delete=0, to='main_app.TestCalibration')),
            ],
        ),
    ]
