# Generated by Django 2.1.7 on 2019-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190311_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpg',
            name='tower_code',
            field=models.ForeignKey(on_delete=0, to='main_app.Tower'),
        ),
    ]
