# Generated by Django 2.1.7 on 2019-03-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_testcalibration_testequipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testequipment',
            name='calibrations',
        ),
        migrations.DeleteModel(
            name='TestCalibration',
        ),
        migrations.DeleteModel(
            name='TestEquipment',
        ),
    ]
