# Generated by Django 2.1.7 on 2019-03-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190311_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpg',
            name='tower_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
