# Generated by Django 2.1.7 on 2019-03-13 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190311_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpg',
            name='time_stamp',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='datasetpg',
            name='tower_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
