# Generated by Django 2.1.7 on 2019-03-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190321_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='testequipment',
            name='calibrations',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.TestCalibration'),
        ),
    ]
