# Generated by Django 2.1.7 on 2019-03-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190313_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='group_type',
            field=models.CharField(choices=[('NA', 'None'), ('FT', 'Field Team'), ('PD', 'Project Developer'), ('PF', 'Performance FollowUp')], default='NA', max_length=30),
        ),
    ]
