# Generated by Django 2.1.7 on 2019-03-21 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190321_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcalibration',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.TestEquipment'),
        ),
    ]
