# Generated by Django 2.1.7 on 2019-03-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190321_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClassificationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestConfPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestDimensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestSensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('orientation', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='testcalibration',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.TestEquipment'),
        ),
        migrations.AddField(
            model_name='testsensorconfig',
            name='calibrations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.TestCalibration'),
        ),
        migrations.AddField(
            model_name='testsensorconfig',
            name='confperiods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.TestConfPeriod'),
        ),
        migrations.AddField(
            model_name='testdimensions',
            name='sensorsconfiguration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.TestSensorConfig'),
        ),
        migrations.AddField(
            model_name='testclassificationperiod',
            name='sensorsconfiguration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.TestSensorConfig'),
        ),
    ]
