# Generated by Django 2.1.7 on 2019-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190321_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcalibration',
            name='slope',
            field=models.FloatField(null=True),
        ),
    ]
