# Generated by Django 2.1.7 on 2019-03-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190315_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='id',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
