# Generated by Django 2.1.7 on 2019-03-17 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190315_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpg',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='datasetpg',
            name='tower_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['tower_code', 'time_stamp'], name='main_app_da_tower_c_6a0ada_idx'),
        ),
    ]
