# Generated by Django 2.1.7 on 2019-03-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190321_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.FloatField()),
                ('slope', models.FloatField()),
                ('calib_date', models.DateField(blank=True, null=True)),
                ('ref', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.EquipmentType'),
        ),
        migrations.AddField(
            model_name='calibration',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Equipment'),
        ),
    ]
