# Generated by Django 2.1.7 on 2019-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190317_1916'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['tower_code'], name='main_app_da_tower_c_56bc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['time_stamp'], name='main_app_da_time_st_e0ed7c_idx'),
        ),
    ]
