# Generated by Django 2.1.7 on 2019-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190317_1922'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_tower_c_6a0ada_idx',
        ),
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['tower_code', 'time_stamp', 'value'], name='main_app_da_tower_c_ee99ed_idx'),
        ),
    ]
