# Generated by Django 2.1.7 on 2019-03-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20190321_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='status',
            new_name='is_active',
        ),
    ]
