# Generated by Django 2.1.7 on 2019-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20190317_1929'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['value'], name='main_app_da_value_1a0968_idx'),
        ),
    ]
