# Generated by Django 2.1.7 on 2019-03-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20190317_1930'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_tower_c_ee99ed_idx',
        ),
    ]
