# Generated by Django 2.1.7 on 2019-03-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20190317_1931'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_tower_c_56bc0f_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_time_st_e0ed7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='datasetpg',
            name='main_app_da_value_1a0968_idx',
        ),
        migrations.AddIndex(
            model_name='datasetpg',
            index=models.Index(fields=['tower_code', 'time_stamp'], name='main_app_da_tower_c_6a0ada_idx'),
        ),
    ]
