# Generated by Django 2.1.7 on 2019-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_periodconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodconfiguration',
            name='begin_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='periodconfiguration',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
