# Generated by Django 2.1.7 on 2019-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20190317_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='towers',
            field=models.ManyToManyField(null=True, to='main_app.Tower', verbose_name='list of towers'),
        ),
    ]
