# Generated by Django 2.1.7 on 2019-03-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20190327_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcharacteristic',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='type',
        ),
    ]
