# Generated by Django 2.1.7 on 2019-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20190318_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='towers',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.Tower', verbose_name='list of towers'),
        ),
    ]
