# Generated by Django 2.1.7 on 2019-03-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20190327_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.EquipmentCharacteristic'),
        ),
    ]
