# Generated by Django 2.1.7 on 2019-03-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20190327_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdates',
            name='tower',
        ),
        migrations.RemoveField(
            model_name='testdates',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testuser',
            name='members',
        ),
        migrations.DeleteModel(
            name='TestDates',
        ),
        migrations.DeleteModel(
            name='TestTower',
        ),
        migrations.DeleteModel(
            name='TestUser',
        ),
    ]
