# Generated by Django 2.1.7 on 2019-03-28 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20190328_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tower')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='towers',
        ),
        migrations.AddField(
            model_name='myuser',
            name='towers',
            field=models.ManyToManyField(blank=True, through='main_app.Dates', to='main_app.Tower',
                                         verbose_name='list of towers'),
        ),
        migrations.AddField(
            model_name='dates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
