# Generated by Django 2.1.7 on 2019-03-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20190328_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dates',
            new_name='UserTowerDates',
        ),
    ]
