# Generated by Django 2.1.7 on 2019-03-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20190318_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birthdate',
        ),
    ]
