# Generated by Django 2.1.7 on 2019-03-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20190328_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdates',
            name='tower',
            field=models.ManyToManyField(blank=True, to='main_app.TestTower'),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='members',
            field=models.ManyToManyField(blank=True, to='main_app.TestDates'),
        ),
    ]
