# Generated by Django 2.1.7 on 2019-03-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20190328_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertowerdates',
            name='begin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usertowerdates',
            name='end_date',
            field=models.DateField(),
        ),
    ]
