# Generated by Django 2.1.7 on 2019-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20190318_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
