# Generated by Django 2.1.7 on 2019-03-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20190328_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.ManyToManyField(blank=True, to='main_app.TestDates')),
            ],
        ),
        migrations.AddField(
            model_name='testdates',
            name='tower',
            field=models.ManyToManyField(blank=True, to='main_app.TestTower'),
        ),
        migrations.AddField(
            model_name='testdates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.TestUser'),
        ),
    ]
