# Generated by Django 2.1.7 on 2019-03-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20190328_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='towers',
        ),
        migrations.AddField(
            model_name='myuser',
            name='towers',
            field=models.ManyToManyField(blank=True, to='main_app.UserTowerDates'),
        ),
        migrations.RemoveField(
            model_name='usertowerdates',
            name='tower',
        ),
        migrations.AddField(
            model_name='usertowerdates',
            name='tower',
            field=models.ManyToManyField(blank=True, to='main_app.Tower'),
        ),
    ]
