# Generated by Django 2.1.7 on 2019-04-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20190329_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('height_label', models.CharField(blank=True, max_length=20, null=True)),
                ('orientation', models.FloatField(blank=True, null=True)),
                ('boom_length', models.FloatField(blank=True, null=True)),
                ('boom_var_height', models.FloatField(blank=True, null=True)),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Calibration')),
                ('conf_period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.PeriodConfiguration')),
            ],
        ),
    ]
