# Generated by Django 2.1.7 on 2019-04-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_equipmentconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
