# Generated by Django 2.1.7 on 2019-04-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_auto_20190409_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.FloatField(unique=True),
        ),
    ]
