# Generated by Django 2.1.7 on 2019-04-09 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_auto_20190409_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('equipment_configuration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.EquipmentConfig')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
