# Generated by Django 2.1.7 on 2019-04-16 13:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_auto_20190415_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('internal_comment', models.TextField(blank=True, null=True)),
                ('compact_comment', models.TextField(blank=True, null=True)),
                ('detailed_comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testcalibration',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='testequipment',
            name='calibrations',
        ),
        migrations.RemoveField(
            model_name='testsensorconfig',
            name='calibrations',
        ),
        migrations.RemoveField(
            model_name='testsensorconfig',
            name='confperiods',
        ),
        migrations.CreateModel(
            name='TestCommentTower',
            fields=[
                ('testcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.TestComment')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Tower')),
            ],
            bases=('main_app.testcomment',),
        ),
        migrations.DeleteModel(
            name='TestCalibration',
        ),
        migrations.DeleteModel(
            name='TestConfPeriod',
        ),
        migrations.DeleteModel(
            name='TestEquipment',
        ),
        migrations.DeleteModel(
            name='TestSensorConfig',
        ),
        migrations.AddField(
            model_name='testcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
