# Generated by Django 2.1.7 on 2019-04-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_auto_20190416_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testcommenttower',
            name='testcomment_ptr',
        ),
        migrations.RemoveField(
            model_name='testcommenttower',
            name='tower',
        ),
        migrations.DeleteModel(
            name='TestComment',
        ),
        migrations.DeleteModel(
            name='TestCommentTower',
        ),
    ]
