# Generated by Django 2.1.7 on 2019-04-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_testcommentclassification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcommentclassification',
            old_name='tower',
            new_name='classification',
        ),
    ]
