# Generated by Django 2.1.7 on 2019-04-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_auto_20190416_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentclassification',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='commentclassification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commenttower',
            name='tower',
        ),
        migrations.RemoveField(
            model_name='commenttower',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentClassification',
        ),
        migrations.DeleteModel(
            name='CommentTower',
        ),
    ]
