# Generated by Django 2.1.7 on 2019-04-18 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_commentclassification_commenttower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentclassification',
            name='begin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commentclassification',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commenttower',
            name='begin_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='commenttower',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
