# Generated by Django 2.1.7 on 2019-04-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_equipmenttype_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='initials',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
