# Generated by Django 2.1.7 on 2019-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_auto_20190424_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='code_aux_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='code_aux_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='code_client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='coords_system',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='gsm_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='parish',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='position_x',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='machine',
            name='position_y',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='machine',
            name='project',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='utm_zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='code_aux_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='code_aux_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='code_client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='coords_system',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tower',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='gsm_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='parish',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='position_x',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='tower',
            name='position_y',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='tower',
            name='project',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tower',
            name='utm_zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
