# Generated by Django 2.1.7 on 2019-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0060_auto_20190424_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
