# Generated by Django 2.1.7 on 2019-04-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_auto_20190424_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentconfig',
            name='dimension_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.DimensionType'),
        ),
    ]
