# Generated by Django 2.1.7 on 2019-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_equipmentconfig_dimension_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentconfig',
            name='dimension_type',
        ),
    ]
