# Generated by Django 2.1.7 on 2019-05-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_auto_20190425_1229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classificationperiod',
            unique_together={('begin_date', 'end_date', 'equipment_configuration', 'status')},
        ),
    ]
