# Generated by Django 2.1.7 on 2019-05-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0069_auto_20190513_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentclassification',
            unique_together={('begin_date', 'end_date', 'classification')},
        ),
        migrations.AlterUniqueTogether(
            name='commenttower',
            unique_together={('begin_date', 'end_date', 'tower')},
        ),
    ]
