# Generated by Django 2.1.7 on 2019-05-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0070_auto_20190513_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classificationperiod',
            unique_together={('begin_date', 'end_date', 'equipment_configuration')},
        ),
    ]
