# Generated by Django 2.1.7 on 2019-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0071_auto_20190515_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentconfig',
            name='offset_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentconfig',
            name='slope_dl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
