# Generated by Django 2.1.7 on 2019-05-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0072_auto_20190516_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcharacteristic',
            name='offset_stn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentcharacteristic',
            name='slope_stn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
