# Generated by Django 2.1.7 on 2019-05-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0073_auto_20190516_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentconfig',
            name='height_label',
            field=models.CharField(max_length=50),
        ),
    ]
