# Generated by Django 2.1.7 on 2019-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='novo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
