# Generated by Django 2.1.7 on 2019-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxData',
            fields=[
                ('time', models.DateTimeField(db_column='time', primary_key=True, serialize=False)),
                ('value', models.CharField(db_column='value', max_length=100)),
            ],
        ),
    ]
